#!/usr/bin/env bash
################################################################################
#                                                                              #
#          SHARE ZSCALER VPN TUNNEL OF ANOTHER_HOST / VIRTUAL MACHINE          #
#                                                                              #
#            - REQUIRES A MACHINE WITH A RUNNING ZSCALER INSTANCE -            #
#          Instructions for setting up such a machine can be found at          #
#           https://github.com/bkahlert/kill-zscaler#sharing-zscaler           #
#                                                                              #
################################################################################

declare share_script
share_script=$(cat <<'SHARE_SCRIPT'
bash -c "$(curl -so- https://raw.githubusercontent.com/bkahlert/kill-zscaler/main/share-zscaler.v2.sh)" -- \
  --domain ceiwrrooyahl.eu-central-1.rds.amazonaws.com \
  --domain codefactory.sh \
  --domain dkb.de \
  --domain dkb.ag \
  --domain dkb.f-i-apim.de \
  --domain etap.f-i-apim.de \
  --domain intern \
  --domain vpce-svc-0d62585dbe3bc5d15.eu-central-1.vpce.amazonaws.com \
  --domain vpce-svc-0e704227530f65d5f.eu-central-1.vpce.amazonaws.com \
  --domain ax4z.com \
  --probe api.developer.qa.dkb.de
SHARE_SCRIPT
)

declare remote_share_script
remote_share_script=$(cat <<'REMOTE_SHARE_SCRIPT'
REMOTE_SHARE_USER='zscaler'
REMOTE_SHARE_HOST_PORT='22'
REMOTE_SHARE_HOST_IP_RANGE='192.168.206.2-254'
REMOTE_SHARE_HOST=$(sudo nmap -n -p "$REMOTE_SHARE_HOST_PORT" "$REMOTE_SHARE_HOST_IP_RANGE" -oG - | awk '/Up$/{print $2}')
printf '%sShare using %s@%s:%s ...%s\n' "$(tput bold)" "$REMOTE_SHARE_USER" "$REMOTE_SHARE_HOST" "$REMOTE_SHARE_HOST_PORT" "$(tput sgr0)" >&2
REMOTE_SHARE_SCRIPT
# shellcheck disable=SC2016
printf 'ssh -4 -p "$REMOTE_SHARE_HOST_PORT" "$REMOTE_SHARE_USER@$REMOTE_SHARE_HOST" %q\n' "$share_script"
)

# Runs the share invocation on the (remote) machine REMOTE_SHARE_HOST
# which outputs a host configuration script.
# The host configuration is piped to this machine's Bash
# to finalize the share.
share() {
  bash -c "$remote_share_script" | bash

  # Alternatively use the following command instead
  # to invoke the share script on the Zscaler host itself.
  # (In this case the output configuration script needs to be executed
  #  on the host wanting to make use of the shared connection manually.)
  # bash -c "$share_script"
}

# Runs the undo host configuration script
# implicitly created by share.
# shellcheck disable=SC2120
unshare() {
  local command=${1:-$HOME/unshare-zscaler.v2.sh}
  if [ -x "$command" ]; then
    "$command"
  fi
}

# Creates a 'un'-prefixed symbolic link to this script next to it
create_unshare_symlink() {
  (cd "${0%/*}" || exit; ln -shf "${0##*/}" "un${0##*/}")
}

# Runs share by default or unshare
# if the 'un'-prefixed symbolic link is called.
main() {
  case $0 in
    */share*)
      create_unshare_symlink
      share
      ;;
    */unshare*)
      unshare
      ;;
  esac
}

main "$@"
