#!/bin/bash
# Runs command in Alpine container (interactive if no args)
# Usage: alpine [command...]
cmd=(docker run --rm -e LANG=C.UTF-8 -e TERM="$TERM")
if [[ $# == 0 ]]; then
  "${cmd[@]}" -it docker:20.10.10-alpine3.14 /bin/sh
else
  "${cmd[@]}" docker:20.10.10-alpine3.14 sh -c "$*"
fi
