#!/bin/bash
# Runs command in BusyBox container with cwd mounted
# Usage: busybox-here [command...]
cmd=(docker run --rm -e LANG=C.UTF-8 -e TERM="$TERM" -v "$PWD:$PWD" -w "$PWD")
if [[ $# == 0 ]]; then
  "${cmd[@]}" -it busybox /bin/sh
else
  "${cmd[@]}" busybox sh -c "$*"
fi
