#!/usr/bin/env bash
#bashsupport disable=BP5004
#
# Usage: notify --host hostname --port port --user user
# Exit codes:
#   0: iTerm2 shell integration should be installed
#   1: iTerm2 shell integration must not be installed
#   2: Illegal invocation

if [ "${DEBUG-}" ]; then
  printf 'Invocation: %b\n' "$*" >>~/.iterm-integration.log
fi

if [ $# -eq 0 ]; then
  printf "\033[1mUsage:\033[0m %s --hostname \033[3mhostname\033[23m --port \033[3mport\033[23m --user \033[3muser\033[23m\n" "${0##*/}" >&2
  printf "\033[1mExample:\033[0m %s --hostname \033[3mfoo.local\033[23m --port \033[3m22\033[23m --user \033[3mjohn\033[23m\n" "${0##*/}" >&2
  exit 2
fi

declare -a args
declare hostname port user
while (($#)); do
  case $1 in
  --hostname)
    shift
    [ $# -gt 0 ] || { printf "\033[31m\033[3m%s\033[23m set but the required argument is missing.\033[0m\n" --hostname >&2 && exit 1; }
    hostname=$1 && shift
    ;;
  --port)
    shift
    [ $# -gt 0 ] || { printf "\033[31m\033[3m%s\033[23m set but the required argument is missing.\033[0m\n" --port >&2 && exit 1; }
    port=$1 && shift
    ;;
  --user)
    # ~/Library/Sounds, /System/Library/Sounds
    shift
    [ $# -gt 0 ] || { printf "\033[31m\033[3m%s\033[23m set but the required argument is missing.\033[0m\n" --user >&2 && exit 1; }
    user=$1 && shift
    ;;
  *)
    args+=("$1") && shift
    ;;
  esac
done

declare exit_code=0
for arg in hostname port user; do
  if [ -z "${!arg-}" ]; then
    printf "\033[31m%s \033[3m%s\033[23m missing\033[0m\n" "--$arg" "$arg" >&2
    exit_code=2
  fi
done
[ "$exit_code" -eq 0 ] || exit "$exit_code"

[ "$LC_TERMINAL" = iTerm2 ] || exit 1

case "${hostname%.}" in
unicorn.local|netmon.local)
  case "$user" in
  bkahlert)
    notify "$user@$hostname" --title "👨‍💻${0##*/}"
    exit 0
    ;;
  esac
  ;;
esac

exit 1
