#!/bin/bash
# Generates code for OpenAPI spec
# Usage: openapi [spec-file] [generator]
specFile="${1:-$(find specs -type f \( -iname '*.json' -o -iname '*.yaml' -o -iname '*.yml' \) | head -n 1)}"
generator="${2:-kotlin}"
outDir="out/${generator}"
absOutDir="$PWD/${outDir}"
echo "Generating ${generator} code for ${specFile} at ${absOutDir}"
mkdir -p "${absOutDir}"
docker run --rm -v "$PWD:/local" openapitools/openapi-generator-cli generate \
  -i "/local/${specFile}" \
  -g "${generator}" \
  -o "/local/${outDir}"
