#!/bin/bash
# Runs command in BusyBox container (interactive if no args)
# Usage: busybox [command...]
cmd=(docker run --rm -e LANG=C.UTF-8 -e TERM="$TERM")
if [[ $# == 0 ]]; then
  "${cmd[@]}" -it busybox /bin/sh
else
  "${cmd[@]}" busybox sh -c "$*"
fi
