#!/bin/bash
# Runs command in Ubuntu container with cwd mounted
# Usage: ubuntu-here [command...]
cmd=(docker run --rm -e LANG=C.UTF-8 -e TERM="$TERM" -v "$PWD:$PWD" -w "$PWD")
if [[ $# == 0 ]]; then
  "${cmd[@]}" -it ubuntu /bin/bash
else
  "${cmd[@]}" ubuntu bash -c "$*"
fi
