#!/bin/bash
# Generates code for Swagger/OpenAPI spec
# Usage: swagger [spec-file] [language]
specFile="${1:-$(find specs -type f \( -iname '*.json' -o -iname '*.yaml' -o -iname '*.yml' \) | head -n 1)}"
lang="${2:-kotlin}"
outDir="out/${lang}"
absOutDir="$PWD/${outDir}"
echo "Generating ${lang} code for ${specFile} at ${absOutDir}"
mkdir -p "${absOutDir}"
docker run --rm -v "$PWD:/local" swaggerapi/swagger-codegen-cli generate \
  -i "/local/${specFile}" \
  -l "${lang}" \
  -o "/local/${outDir}"
