#!/usr/bin/env bash
# Purpose: Send a macOS notification via osascript's `display notification`.
# Usage:   notify <message> [--title <title>] [--subtitle <subtitle>] [--sound <sound>]
#
# Sounds are looked up in ~/Library/Sounds and /System/Library/Sounds.
# Set DEBUG=1 to log invocations to ~/.notify.log.

if [ "${DEBUG-}" ]; then
  printf 'Invocation: %b\n' "$*" >>~/.notify.log
fi

# Joins remaining args with first arg.
join_by() {
  local d=${1-} f=${2-}
  if shift 2; then
    printf %s "$f" "${@/#/$d}"
  fi
}

if [ $# -eq 0 ]; then
  printf "\e[1mUsage:\e[0m %s \e[3mmessage\e[23m [--title \e[3mtitle\e[23m] [--subtitle \e[3msub-title\e[23m] [--sound \e[3msound\e[23m]\n" "${0##*/}" >&2
  printf "\e[1mExample:\e[0m %s \e[3m'%s'\e[23m --title \e[3m'%s'\e[23m --sound \e[3m%s\e[23m\n" "${0##*/}" "You have just been notified" "🎉 Congratulations" purr >&2
  exit 1
fi

declare -a args
declare title subtitle sound
while (($#)); do
  case $1 in
  --title)
    shift
    [ $# -gt 0 ] || { printf "\e[31m\e[3m%s\e[23m set but the required argument is missing.\e[0m\n" --title >&2 && exit 1; }
    title=$1 && shift
    ;;
  --subtitle)
    shift
    [ $# -gt 0 ] || { printf "\e[31m\e[3m%s\e[23m set but the required argument is missing.\e[0m\n" --subtitle >&2 && exit 1; }
    subtitle=$1 && shift
    ;;
  --sound)
    # ~/Library/Sounds, /System/Library/Sounds
    shift
    [ $# -gt 0 ] || { printf "\e[31m\e[3m%s\e[23m set but the required argument is missing.\e[0m\n" --sound >&2 && exit 1; }
    sound=$1 && shift
    ;;
  *)
    args+=("$1") && shift
    ;;
  esac
done

notification=$(join_by ' ' "${args[@]}")

# AppleScript sucks
osascript - "$notification" "${title:-Notification}" "$subtitle" "$sound" <<EOF
  on run {theNotification, theTitle, theSubtitle, theSound}
    if theSound is "" then
      display notification theNotification with title theTitle subtitle theSubtitle
    else
      display notification theNotification with title theTitle subtitle theSubtitle sound name theSound
    end if
  end run
EOF
