#!/usr/bin/env bash

set -euo pipefail
source <(curl -LfsS https://github.com/bkahlert/logr/raw/master/logr.sh)

banr diff preferences

# Check for bash; the usage of read is different in zsh
interpreter="$(ps h -p $$ -o args='' | cut -f1 -d' ')"
if [ ! "$interpreter" = "bash" ]; then
  echo >&2 "This script must be called with bash."
  exit 1
fi

logr task "preparing" -- bash -c 'defaults read > /tmp/prefs.before'

logr info "You can customize your configuration now."

prompt4 Y/n '%s\n' "As soon as you have finished, hit Enter to see the changed defaults." \
                  "Ready?"

defaults read > /tmp/prefs.after
sed -i '' \
  -e '/[Dd]uration\ \{0,1\}=/d' \
  -e '/[0-9]\{4,\}[-\/][0-9]\{2\}[-\/][0-9]\{2\}[T ][0-9]\{2\}:[0-9]\{2\}/d' \
  -e '/[0-9]\{2,\}[-\/][0-9]\{2\}[-\/][0-9]\{4\}[T ][0-9]\{2\}:[0-9]\{2\}/d' \
  /tmp/prefs.before /tmp/prefs.after
diff --unified=3 \
  /tmp/prefs.before /tmp/prefs.after &
command -v "idea" >/dev/null && idea --wait diff /tmp/prefs.before /tmp/prefs.after
rm /tmp/prefs.before /tmp/prefs.after
